import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // The two calendar libraries are vendored (see vendor/) so the plugin
  // has no runtime npm dependencies; resolve their bare specifiers there.
  alias: {
    "obsidian-calendar-ui": "./vendor/obsidian-calendar-ui/index.js",
    "obsidian-daily-notes-interface": "./vendor/obsidian-daily-notes-interface/index.js",
  },
  plugins: [
    esbuildSvelte({
      compilerOptions: { css: false },
      preprocess: sveltePreprocess(),
    }),
  ],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
